document.write("<li>")
document.write("<a href='index.html'>Home</a>")
document.write("</li>")
document.write("<li>")
document.write("<a href='about.html'>Quem somos</a>")
document.write("</li>")
document.write("<li>")
document.write("<a href='services2.html'>Serviços</a>")
document.write("</li>")
document.write("<li class='dropdown'><a href='#'>Cases</a>")
document.write("<ul>")
document.write("<li><a href='projects.html'>Cases Type 01</a></li>")
document.write("<li><a href='projects-2.html'>Cases Type 02</a></li>")
document.write("</ul>")
document.write("</li>")
document.write("<li><a href='contact.html'>Contato</a></li>")
document.write("</ul>")