document.write("<div class='big-column col-md-12 col-sm-12 col-xs-12'>")
document.write("<div class='row clearfix'>")
document.write("<div class='footer-column col-md-5 col-sm-6 col-xs-12'>")
document.write("<div class='footer-widget about-widget'>")
document.write("<div class='widget-inner'>")
document.write("<div class='logo'><img src='images/footer-logo.png' alt=''></div>")
document.write("<div class='text'>Nulla ac nunc eget ante consectetur lobortis a vel orci. Vivamus nibh est condimentum ac metus nec, gravida varius diam.</div>")
document.write("<div class='social-links'>")
document.write("<ul class='clearfix'>")
document.write("<li><a href='#'><span class='fa fa-facebook-f'></span></a></li>")
document.write("<li><a href='#'><span class='fa fa-instagram'></span></a></li>")
document.write("<li><a href='#'><span class='fa fa-linkedin'></span></a></li>")
document.write("</ul>")
document.write("</div>")
document.write("</div>")
document.write("</div>")
document.write("</div>")
document.write("<div class='footer-column col-md-4 col-sm-6 col-xs-12'>")
document.write("<div class='footer-widget links-widget'>")
document.write("<div class='widget-inner'>")
document.write("<h3>Serviços</h3>")
document.write("<div class='links'>")
document.write("<ul>")
document.write("<li><a href='#'>Departamento Contábil</a></li>")
document.write("<li><a href='#'>Departamento Pessoal</a></li>")
document.write("<li><a href='#'>Departamento Fiscal</a></li>")
document.write("<li><a href='#'>Abertura de empresas</a></li>")
document.write("</ul>")
document.write("</div>")
document.write("</div>")
document.write("</div>")
document.write("</div>")
document.write("<div class='footer-column col-md-3 col-sm-6 col-xs-12'>")
document.write("<div class='footer-widget info-widget'>")
document.write("<div class='widget-inner'>")
document.write("<h3>Contact Us</h3>")
document.write("<div class='info'>")
document.write("<ul>")
document.write("<li class='clearfix'><strong><i class='fa fa-map-marker'></i></strong> <span class='txt'>Rua Lino Coutinho n° 1.438<br>Ipiranga - São Paulo <br>04207-001</span></li>")
document.write("<li class='clearfix'><strong><i class='fa fa-phone'></i></strong> <span class='txt'>+55 11 2273-1733</span></li>")
document.write("<li class='clearfix'><strong><i class='fa fa-envelope-o'></i></strong> <span class='txt'>contabil@mairro.com.br</span></li>")
document.write("</ul>")
document.write("</div>")
document.write("</div>")
document.write("</div>")
document.write("</div>")
document.write("</div>")
document.write("</div>")